/*
 * A. Benquerer
 * e-mail: dev.benquerer@gmail.com
 * GitHub: https://github.com/Benquerer
 * 
 * Aluno 24633 @ IPT, Oct 2024.
 * 
 * The code in this file was developed for learning and experimentation purposes.
 * 
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.nio.file.Files;
import java.nio.file.Path;
import java.rmi.RemoteException;
import java.util.Base64;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import p2p.IremoteP2P;
import utils.Curriculum;
import utils.RMI;
import utils.User;
import utils.Wallet;
import utils.app_params;

/**
 * This frame implements the main application, for a logged user
 *
 * @author A. Benquerer @ IPT
 * @author D. Larangeira @ IPT
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Client using the application
     */
    User client = null;

    Wallet clientWallet;

    /**
     * Node in P2P Network that the client connects to
     */
    IremoteP2P remote;

    /**
     * List used as logged user's "wallet"
     */
    DefaultListModel<String> userCurricula = new DefaultListModel();

    /**
     * List used to store the curricula from a search
     */
    DefaultListModel<String> searchResults = new DefaultListModel();

    /**
     * Creates the main application frame
     *
     * @deprecated Use
     * {@link ApplicationFrame#ApplicationFrame(utils.User, javax.swing.LookAndFeel)}
     * instead.
     */
    @Deprecated
    public ClientFrame() {
        //netbeans init code
        initComponents();
        //center app frame
        this.setLocationRelativeTo(null);

    }

    /**
     * Creates the main application frame with a predetermined LaF and
     * determines a user currently logged in to the app.
     *
     * @param loggedUser User that logged in via the login frame
     * @param laf LaF to use in the app
     */
    public ClientFrame(User loggedUser, LookAndFeel laf, String address) throws Exception {
        //use passed in laf 
        try {
            UIManager.setLookAndFeel(laf);
        } catch (UnsupportedLookAndFeelException ex) {

        }
        //netbeans init code
        initComponents();
        //center and display the app frame
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        //define loggedUser
        this.client = loggedUser;
        //use username in title, main menu and wallet
        this.setTitle(app_params.APP_NAME + " (Logged as " + loggedUser.getUserName() + ")");
        lblWelcome.setText("Welcome, " + loggedUser.getUserName() + "!");

        txtNumCurricula.setText("loading");

        //Connect to node in P2P Network
        remote = (IremoteP2P) RMI.getRemote(address);

        //thread para atualizar a carteira
        new Thread(() -> {
            try {
                //criar a wallet
                //se ja existe uma wallet
                if (Files.exists(Path.of(client.getUserName() + ".wlt"))) {
                    this.clientWallet = Wallet.loadWallet(client.getUserName(), client.getSimKey().getEncoded());
                    //dar update da wallet
                    clientWallet.updateWallet(remote.getUserWallet(client.getUserName(), clientWallet.getMerkleReferences()));
                    //salva a wallet
                    clientWallet.saveWallet();
                } else { //nao existe

                    //cria a wallet
                    this.clientWallet = new Wallet(client.getUserName(), client.getSimKey());
                    //dar update da wallet
                    clientWallet.updateWallet(remote.getUserWallet(client.getUserName(), clientWallet.getMerkleReferences()));
                    //salva a wallet
                    clientWallet.saveWallet();
                }
                //carregar na lista
                List<String> res = clientWallet.getAllCurricula();
                userCurricula.addAll(res);
                SwingUtilities.invokeLater(() -> {
                    txtNumCurricula.setText(String.valueOf(res.size()));
                });
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnSignOut = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        lblWalletName1 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        listUserCurricula = new javax.swing.JList<>();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtWalletFrom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtWalletValid = new javax.swing.JTextField();
        btnWalletProof = new javax.swing.JButton();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtWalletDesc = new javax.swing.JTextArea();
        jPanel43 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtNumCurricula = new javax.swing.JTextField();
        btnUpdateWallet = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSearchRes = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSrchFrom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSrchValid = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSrchDesc = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumRes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 650));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnSignOut.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignOut);

        btnQuit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQuit.setText("Quit ");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuit);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png"))); // NOI18N
        lblTitle.setText(utils.app_params.APP_NAME);
        jPanel3.add(lblTitle);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 25));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblWelcome.setText("Welcome USERNAME!");
        jPanel18.add(lblWelcome);

        jPanel1.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10));

        lblWalletName1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblWalletName1.setText("Your Curricula:");
        jPanel36.add(lblWalletName1);

        jPanel11.add(jPanel36, java.awt.BorderLayout.PAGE_START);

        jPanel37.setLayout(new java.awt.BorderLayout());

        jSplitPane3.setDividerLocation(230);
        jSplitPane3.setDividerSize(0);

        listUserCurricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listUserCurricula.setModel(userCurricula);
        listUserCurricula.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listUserCurriculaValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(listUserCurricula);

        jSplitPane3.setLeftComponent(jScrollPane7);

        jPanel38.setLayout(new java.awt.BorderLayout());

        jPanel39.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Registrant:");
        jPanel39.add(jLabel14);

        txtWalletFrom.setEditable(false);
        txtWalletFrom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtWalletFrom.setMaximumSize(new java.awt.Dimension(180, 42));
        txtWalletFrom.setMinimumSize(new java.awt.Dimension(180, 42));
        txtWalletFrom.setPreferredSize(new java.awt.Dimension(180, 42));
        jPanel39.add(txtWalletFrom);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Status:");
        jPanel39.add(jLabel15);

        txtWalletValid.setEditable(false);
        txtWalletValid.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtWalletValid.setMaximumSize(new java.awt.Dimension(134, 42));
        txtWalletValid.setMinimumSize(new java.awt.Dimension(134, 42));
        txtWalletValid.setPreferredSize(new java.awt.Dimension(134, 42));
        jPanel39.add(txtWalletValid);

        btnWalletProof.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnWalletProof.setText("Proof");
        btnWalletProof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWalletProofActionPerformed(evt);
            }
        });
        jPanel39.add(btnWalletProof);

        jPanel38.add(jPanel39, java.awt.BorderLayout.PAGE_START);

        jPanel40.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel41.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Description:");
        jPanel41.add(jLabel16);

        jPanel40.add(jPanel41, java.awt.BorderLayout.PAGE_START);

        jPanel42.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jScrollPane8.setPreferredSize(new java.awt.Dimension(600, 290));

        txtWalletDesc.setEditable(false);
        txtWalletDesc.setColumns(20);
        txtWalletDesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtWalletDesc.setRows(5);
        jScrollPane8.setViewportView(txtWalletDesc);

        jPanel42.add(jScrollPane8);

        jPanel40.add(jPanel42, java.awt.BorderLayout.CENTER);

        jPanel38.add(jPanel40, java.awt.BorderLayout.CENTER);

        jSplitPane3.setRightComponent(jPanel38);

        jPanel37.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        jPanel43.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Results: ");
        jPanel43.add(jLabel17);

        txtNumCurricula.setEditable(false);
        txtNumCurricula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNumCurricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumCurricula.setMaximumSize(new java.awt.Dimension(80, 30));
        txtNumCurricula.setMinimumSize(new java.awt.Dimension(80, 30));
        txtNumCurricula.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel43.add(txtNumCurricula);

        btnUpdateWallet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateWallet.setText("Update Wallet");
        btnUpdateWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateWalletActionPerformed(evt);
            }
        });
        jPanel43.add(btnUpdateWallet);

        jPanel37.add(jPanel43, java.awt.BorderLayout.PAGE_END);

        jPanel11.add(jPanel37, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel11, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Home", jPanel1);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Username:");
        jPanel7.add(jLabel1);

        txtUserSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUserSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel7.add(txtUserSearch);

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel7.add(btnSearch);

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(230);
        jSplitPane1.setDividerSize(0);

        listSearchRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listSearchRes.setModel(searchResults);
        listSearchRes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSearchResValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listSearchRes);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Registrant:");
        jPanel26.add(jLabel6);

        txtSrchFrom.setEditable(false);
        txtSrchFrom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSrchFrom.setMaximumSize(new java.awt.Dimension(180, 42));
        txtSrchFrom.setMinimumSize(new java.awt.Dimension(180, 42));
        txtSrchFrom.setPreferredSize(new java.awt.Dimension(180, 42));
        jPanel26.add(txtSrchFrom);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Status:");
        jPanel26.add(jLabel8);

        txtSrchValid.setEditable(false);
        txtSrchValid.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSrchValid.setMaximumSize(new java.awt.Dimension(134, 42));
        txtSrchValid.setMinimumSize(new java.awt.Dimension(134, 42));
        txtSrchValid.setPreferredSize(new java.awt.Dimension(134, 42));
        jPanel26.add(txtSrchValid);

        jPanel9.add(jPanel26, java.awt.BorderLayout.PAGE_START);

        jPanel25.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Description:");
        jPanel27.add(jLabel9);

        jPanel25.add(jPanel27, java.awt.BorderLayout.PAGE_START);

        jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jScrollPane5.setPreferredSize(new java.awt.Dimension(600, 290));

        txtSrchDesc.setEditable(false);
        txtSrchDesc.setColumns(20);
        txtSrchDesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSrchDesc.setRows(5);
        jScrollPane5.setViewportView(txtSrchDesc);

        jPanel28.add(jScrollPane5);

        jPanel25.add(jPanel28, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel25, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel9);

        jPanel8.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Results: ");
        jPanel10.add(jLabel2);

        txtNumRes.setEditable(false);
        txtNumRes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNumRes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumRes.setMaximumSize(new java.awt.Dimension(80, 30));
        txtNumRes.setMinimumSize(new java.awt.Dimension(80, 30));
        txtNumRes.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel10.add(txtNumRes);

        jPanel8.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Curriculum Lookup", jPanel4);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles quitting the app as a whole, without going back to the login
     * frame.
     *
     * @param evt quit button clicked
     */
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        //Verify if the user really wants to quit
        int confirmation = JOptionPane.showConfirmDialog(this,
                """
                Exit application now?
                This action will logout your
                user and close the application
                (Unsaved actions will be lost!!)
                """,
                "Exiting Application",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.ERROR_MESSAGE);
        //if so, quit
        if (confirmation == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * Handles logging out of the app, returning the user to the main login
     * frame.
     *
     * @param evt sign out button was clicked.
     */
    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        //Verify if the user want to logout
        int confirmation = JOptionPane.showConfirmDialog(this,
                """
                Logout now?
                This action will return you
                to the login page.
                (Unsaved actions will be lost!!)
                """,
                "Exiting Application",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.ERROR_MESSAGE);
        //if so, logout (window closed event will return to loginpage)
        if (confirmation == JOptionPane.YES_OPTION) {
            //make user is logged out
            client = null;
            //dispose
            this.dispose();
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchTarget = txtUserSearch.getText();
        //limpa a lista
        searchResults.clear();
        btnSearch.setEnabled(false);
        try{
            if (remote.userExists(searchTarget)) {
                //search thread
                new Thread(() -> {
                    try {
                        List<String> res = remote.searchUserCurricula(searchTarget);
                        //atualiza a lista
                        searchResults.addAll(res);
                        SwingUtilities.invokeLater(() -> {
                            txtNumRes.setText(String.valueOf(res.size()));
                            JOptionPane.showMessageDialog(rootPane, "Your search returned " + res.size() + " results.", "Search successful", JOptionPane.INFORMATION_MESSAGE);
                            btnSearch.setEnabled(true);
                        });
                    } catch (RemoteException ex) {
                        ex.printStackTrace();
                    }
                }).start();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Referenced user not found!", "Can't Find User", JOptionPane.ERROR_MESSAGE);
                btnSearch.setEnabled(true);
            }
        }catch(RemoteException ex){
            JOptionPane.showMessageDialog(rootPane, "Error during the operation on the server side\n Please try again later..", "ERROR", JOptionPane.ERROR_MESSAGE);
            btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateWalletActionPerformed
        //thread para atualizar a carteira
        new Thread(() -> {
            try {
                //criar a wallet
                //se ja existe uma wallet
                if (Files.exists(Path.of(client.getUserName() + ".wlt"))) {
                    this.clientWallet = Wallet.loadWallet(client.getUserName(), client.getSimKey().getEncoded());
                    //dar update da wallet
                    clientWallet.updateWallet(remote.getUserWallet(client.getUserName(), clientWallet.getMerkleReferences()));
                    //salva a wallet
                    clientWallet.saveWallet();
                } else { //nao existe

                    //cria a wallet
                    this.clientWallet = new Wallet(client.getUserName(), client.getSimKey());
                    //dar update da wallet
                    clientWallet.updateWallet(remote.getUserWallet(client.getUserName(), clientWallet.getMerkleReferences()));
                    //salva a wallet
                    clientWallet.saveWallet();
                }
                //limpa a lista
                userCurricula.clear();
                //carregar na lista
                List<String> res = clientWallet.getAllCurricula();
                userCurricula.addAll(res);
                SwingUtilities.invokeLater(() -> {
                    txtNumCurricula.setText(String.valueOf(res.size()));
                });
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }).start();
    }//GEN-LAST:event_btnUpdateWalletActionPerformed

    private void btnWalletProofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWalletProofActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Not supported Yet", "WIP", JOptionPane.ERROR_MESSAGE);
        // HOW CAN I DISPLAY THE PROOF
    }//GEN-LAST:event_btnWalletProofActionPerformed

    private void listUserCurriculaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listUserCurriculaValueChanged
        if (!evt.getValueIsAdjusting()) { // check if the selection is over (was printing twice) 
            try {
                //check if the selection is over (was printing twice)
                String transaction = listUserCurricula.getSelectedValue();
                //load curriculum from string
                Curriculum c = Curriculum.fromByteArr(Base64.getDecoder().decode(transaction));
                //display informattion
                txtWalletFrom.setText(c.getEntidade());
                txtWalletDesc.setText(c.getDesc());
                txtWalletValid.setText(c.IsValid() ? "Verified" : "Unverified");
                
            } catch (Exception ex) {
                if(listUserCurricula.getSelectedValue() != null){
                    JOptionPane.showMessageDialog(rootPane, "Error loading transaction information", "ERROR", JOptionPane.ERROR_MESSAGE); 
                }
            }
        }
        
    }//GEN-LAST:event_listUserCurriculaValueChanged

    private void listSearchResValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSearchResValueChanged
         if (!evt.getValueIsAdjusting()) { // check if the selection is over (was printing twice) 
            try {
                //check if the selection is over (was printing twice)
                String transaction = listSearchRes.getSelectedValue();
                //load curriculum from string
                Curriculum c = Curriculum.fromByteArr(Base64.getDecoder().decode(transaction));
                //display informattion
                txtSrchFrom.setText(c.getEntidade());
                txtSrchDesc.setText(c.getDesc());
                txtSrchValid.setText(c.IsValid() ? "Verified" : "Unverified");
                
            } catch (Exception ex) {
                if(listSearchRes.getSelectedValue() != null){
                    JOptionPane.showMessageDialog(rootPane, "Error loading transaction information", "ERROR", JOptionPane.ERROR_MESSAGE); 
                }
            }
        }
    }//GEN-LAST:event_listSearchResValueChanged

    /**
     * The main function of the application
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Change LaF of application (Customized by FlatLaf library
        try {
            //set LaF MacOS Dark
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
            //LaF customization
            UIManager.put("Button.arc", 20);
            UIManager.put("Component.arc", 20);
            UIManager.put("TextComponent.arc", 20);
            UIManager.put("Component.focusWidth", 1);
            UIManager.put("Component.arrowType", "chevron");
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnUpdateWallet;
    private javax.swing.JButton btnWalletProof;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWalletName1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList<String> listSearchRes;
    private javax.swing.JList<String> listUserCurricula;
    private javax.swing.JTextField txtNumCurricula;
    private javax.swing.JTextField txtNumRes;
    private javax.swing.JTextArea txtSrchDesc;
    private javax.swing.JTextField txtSrchFrom;
    private javax.swing.JTextField txtSrchValid;
    private javax.swing.JTextField txtUserSearch;
    private javax.swing.JTextArea txtWalletDesc;
    private javax.swing.JTextField txtWalletFrom;
    private javax.swing.JTextField txtWalletValid;
    // End of variables declaration//GEN-END:variables

}
