/*
 * A. Benquerer
 * e-mail: dev.benquerer@gmail.com
 * GitHub: https://github.com/Benquerer
 * 
 * Aluno 24633 @ IPT, Oct 2024.
 * 
 * The code in this file was developed for learning and experimentation purposes.
 * 
 */
package gui;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.WindowAdapter;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.Key;
import java.security.KeyPair;
import java.util.Collections;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import p2p.IremoteP2P;
import utils.RMI;
import utils.SecurityUtils;
import utils.User;
import utils.app_params;

/**
 * This Frame represents the login frame of the application. It servers as the
 * primary landing page.
 *
 * @author A. Benquerer @ IPT
 * @author D. Larangeira @ IPT
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        //netbeans init code
        initComponents();
        //code to run after init
        myInit();
    }

    /**
     * Custom code that will run right after the initialization of components
     */
    public void myInit() {
        //any custom code for the frame should be here. 
        //certer aux frames 
        RegisterFrame.setLocationRelativeTo(null);
        AboutFrame.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterFrame = new javax.swing.JFrame();
        jPanel15 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtRegUsername = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pwdfRegPass = new javax.swing.JPasswordField();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pwdfRegConfPass = new javax.swing.JPasswordField();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        boxIsOrg = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        btnRegisterUser = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        btnCancelReg = new javax.swing.JButton();
        AboutFrame = new javax.swing.JFrame();
        jPanel36 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel40 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel41 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnl1 = new javax.swing.JPanel();
        pnl2 = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        pnl5 = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        pnl6 = new javax.swing.JPanel();
        pnl7 = new javax.swing.JPanel();
        lblPasswd = new javax.swing.JLabel();
        pwdfLogin = new javax.swing.JPasswordField();
        pnl8 = new javax.swing.JPanel();
        pnl4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtRemoteAddress = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btnQuit = new javax.swing.JButton();
        mbarX = new javax.swing.JMenuBar();
        mMain = new javax.swing.JMenu();
        miRegister = new javax.swing.JMenuItem();
        sp1 = new javax.swing.JPopupMenu.Separator();
        miAbout = new javax.swing.JMenuItem();
        miKnowlBase = new javax.swing.JMenu();
        miAbtBc = new javax.swing.JMenuItem();
        miAbrFlaf = new javax.swing.JMenuItem();
        miAbtAsyCry = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        chkboxColorMode = new javax.swing.JCheckBoxMenuItem();
        miAccColor = new javax.swing.JMenuItem();

        RegisterFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        RegisterFrame.setTitle(utils.app_params.APP_NAME + " - Registration Form");
        RegisterFrame.setMinimumSize(new java.awt.Dimension(664, 500));
        RegisterFrame.setResizable(false);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("New here? Sign up:");
        jPanel10.add(jLabel3);

        jPanel15.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel13.setLayout(new java.awt.GridLayout(0, 4, 20, 25));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel14);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Username:");
        jPanel13.add(jLabel4);

        txtRegUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel13.add(txtRegUsername);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel19);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel17);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Password:");
        jPanel13.add(jLabel6);

        pwdfRegPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel13.add(pwdfRegPass);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel18);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Confirm Password:");
        jPanel13.add(jLabel7);

        pwdfRegConfPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel13.add(pwdfRegConfPass);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel21);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel22);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel23);

        boxIsOrg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boxIsOrg.setText("Certifier Org.");
        jPanel13.add(boxIsOrg);

        jPanel11.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        btnRegisterUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegisterUser.setText("Register Now!");
        btnRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUserActionPerformed(evt);
            }
        });
        jPanel12.add(btnRegisterUser);

        jPanel15.add(jPanel12, java.awt.BorderLayout.PAGE_END);

        RegisterFrame.getContentPane().add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnCancelReg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelReg.setText("Cancel");
        btnCancelReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegActionPerformed(evt);
            }
        });
        jPanel16.add(btnCancelReg);

        RegisterFrame.getContentPane().add(jPanel16, java.awt.BorderLayout.PAGE_END);

        AboutFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AboutFrame.setMinimumSize(new java.awt.Dimension(700, 550));
        AboutFrame.setResizable(false);

        jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setText("About The Project");
        jPanel36.add(jLabel10);

        AboutFrame.getContentPane().add(jPanel36, java.awt.BorderLayout.PAGE_START);

        jPanel29.setLayout(new java.awt.GridLayout(0, 1, 0, 50));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton6.setText("The Project");
        jButton6.setMaximumSize(new java.awt.Dimension(220, 75));
        jButton6.setMinimumSize(new java.awt.Dimension(220, 75));
        jButton6.setPreferredSize(new java.awt.Dimension(220, 75));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel39.add(jButton6);

        jPanel29.add(jPanel39);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton5.setText("Benquerer");
        jButton5.setMaximumSize(new java.awt.Dimension(220, 75));
        jButton5.setMinimumSize(new java.awt.Dimension(220, 75));
        jButton5.setPreferredSize(new java.awt.Dimension(220, 75));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel40.add(jButton5);

        jPanel29.add(jPanel40);

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton7.setText("Larangeira");
        jButton7.setMaximumSize(new java.awt.Dimension(220, 75));
        jButton7.setMinimumSize(new java.awt.Dimension(220, 75));
        jButton7.setPreferredSize(new java.awt.Dimension(220, 75));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel41.add(jButton7);

        jPanel29.add(jPanel41);

        AboutFrame.getContentPane().add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton1);

        AboutFrame.getContentPane().add(jPanel30, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(utils.app_params.APP_NAME);
        setMinimumSize(new java.awt.Dimension(950, 550));
        setResizable(false);

        pnl1.setLayout(new java.awt.GridLayout(0, 1));

        pnl2.setLayout(new java.awt.GridBagLayout());

        lblAppName.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png"))); // NOI18N
        lblAppName.setText(utils.app_params.APP_NAME);
        pnl2.add(lblAppName, new java.awt.GridBagConstraints());

        pnl1.add(pnl2);

        pnl3.setLayout(new java.awt.GridLayout(2, 2, 50, 35));

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        pnl3.add(pnl5);

        lblUserName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUserName.setText("Username:");
        pnl3.add(lblUserName);

        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pnl3.add(txtLogin);

        javax.swing.GroupLayout pnl6Layout = new javax.swing.GroupLayout(pnl6);
        pnl6.setLayout(pnl6Layout);
        pnl6Layout.setHorizontalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnl6Layout.setVerticalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        pnl3.add(pnl6);

        javax.swing.GroupLayout pnl7Layout = new javax.swing.GroupLayout(pnl7);
        pnl7.setLayout(pnl7Layout);
        pnl7Layout.setHorizontalGroup(
            pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnl7Layout.setVerticalGroup(
            pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        pnl3.add(pnl7);

        lblPasswd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPasswd.setText("Password:");
        pnl3.add(lblPasswd);

        pwdfLogin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pnl3.add(pwdfLogin);

        javax.swing.GroupLayout pnl8Layout = new javax.swing.GroupLayout(pnl8);
        pnl8.setLayout(pnl8Layout);
        pnl8Layout.setHorizontalGroup(
            pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnl8Layout.setVerticalGroup(
            pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        pnl3.add(pnl8);

        pnl1.add(pnl3);

        pnl4.setLayout(new java.awt.GridLayout(0, 1));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setPreferredSize(new java.awt.Dimension(150, 52));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);

        pnl4.add(jPanel2);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("New Here? Register now: ");
        jPanel1.add(jLabel2);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        btnRegister.setText("Register");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setPreferredSize(new java.awt.Dimension(140, 27));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegister);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Talking to:     ");
        jPanel1.add(jLabel5);

        txtRemoteAddress.setText("//192.168.1.58:10001/node1");
        jPanel1.add(txtRemoteAddress);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9);

        btnQuit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuit.setText("QUIT");
        btnQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel8.add(btnQuit);

        jPanel1.add(jPanel8);

        pnl4.add(jPanel1);

        pnl1.add(pnl4);

        getContentPane().add(pnl1, java.awt.BorderLayout.CENTER);

        mbarX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mMain.setText("Menu");
        mMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        miRegister.setText("Register");
        miRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegisterActionPerformed(evt);
            }
        });
        mMain.add(miRegister);
        mMain.add(sp1);

        miAbout.setText("About The App");
        miAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        mMain.add(miAbout);

        miKnowlBase.setText("Knowledge Base");

        miAbtBc.setText("Blockchain");
        miAbtBc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbtBcActionPerformed(evt);
            }
        });
        miKnowlBase.add(miAbtBc);

        miAbrFlaf.setText("Asymmetric Encryption");
        miAbrFlaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrFlafActionPerformed(evt);
            }
        });
        miKnowlBase.add(miAbrFlaf);

        miAbtAsyCry.setText("FlatLaF");
        miAbtAsyCry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbtAsyCryActionPerformed(evt);
            }
        });
        miKnowlBase.add(miAbtAsyCry);

        mMain.add(miKnowlBase);
        mMain.add(jSeparator1);

        chkboxColorMode.setSelected(true);
        chkboxColorMode.setText("Dark Mode");
        chkboxColorMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkboxColorMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxColorModeActionPerformed(evt);
            }
        });
        mMain.add(chkboxColorMode);

        miAccColor.setText("Accent Color");
        miAccColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAccColorActionPerformed(evt);
            }
        });
        mMain.add(miAccColor);

        mbarX.add(mMain);

        setJMenuBar(mbarX);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This handles the closing of the application via the quit button
     *
     * @param evt the quit button was clicked
     */
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        //confirm if the user is sure he wants to quit
        int confirmation = JOptionPane.showConfirmDialog(this,
                "Are you sure you want\nto quit the application now?\n(Unsaved actions will be lost!!)",
                "Exiting Application",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.ERROR_MESSAGE);
        if (confirmation == JOptionPane.YES_OPTION) {
            this.dispose(); //dispose of login frame
        }
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * This handles the dark/light mode switch function.
     *
     * @param evt color mode menu change
     */
    private void chkboxColorModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxColorModeActionPerformed
        //check if the darkmode is selected
        boolean isDarkMode = chkboxColorMode.getState();
        //is selected, set to darkmode
        if (isDarkMode) {
            try {
                //set LaF MacOS Dark
                UIManager.setLookAndFeel(new FlatMacDarkLaf());
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            //if not, change to lightmode
            try {
                //set LaF MacOS Dark
                UIManager.setLookAndFeel(new FlatMacLightLaf());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        //update LaF
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(AboutFrame);
        SwingUtilities.updateComponentTreeUI(RegisterFrame);

    }//GEN-LAST:event_chkboxColorModeActionPerformed

    /**
     * This handles the knowledge base topic on Blockchains
     *
     * @param evt menu selected
     */
    private void miAbtBcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbtBcActionPerformed
        try {
            //open the browser with information about the topic
            URI link = new URI(app_params.ABT_BC);
            Desktop.getDesktop().browse(link);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Can't access this information right now!\ntry again later!", "Can't open Link", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_miAbtBcActionPerformed

    /**
     * This handles opening of the registration form via the register button.
     *
     * @param evt register form button clicked
     */
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        RegisterFrame.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * This handles opening of the registration form via menu item.
     *
     * @param evt register form item clicked
     */
    private void miRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegisterActionPerformed
        RegisterFrame.setVisible(true);
    }//GEN-LAST:event_miRegisterActionPerformed

    /**
     * This handles the exit of the registration form via the "cancel" button.
     *
     * @param evt cancel button clicked
     */
    private void btnCancelRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegActionPerformed
        //clear inputs
        txtRegUsername.setText("");
        pwdfRegPass.setText("");
        pwdfRegConfPass.setText("");
        //dispose of frame
        RegisterFrame.dispose();
    }//GEN-LAST:event_btnCancelRegActionPerformed

    /**
     * This handles the display of the about frame.
     *
     * @param evt about menu item clicked
     */
    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        AboutFrame.setVisible(true);
    }//GEN-LAST:event_miAboutActionPerformed

    /**
     * This implements the back button on the about frame.
     *
     * @param evt back button clicked.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AboutFrame.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Handle displaying information about the project
     *
     * @param evt about project button clicked
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JOptionPane.showMessageDialog(rootPane, """
                                                This project is a Java-based application designed for securely registering curricular events on a blockchain. 
                                                Said blockchain utilizes the POW decentralized consensus mechanism, and system leverages Merkle trees for 
                                                efficient data verification and consistency. To enhance user experience, the application incorporates a 
                                                user-friendly interface, allowing seamless and responsive interaction with the system.
                                                This project was developed by André Benquerer and Diogo Larangeira, and was proposed as the main project of
                                                the "Computação Distribuida" class of 2024.
                                                """,
                "About the project", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * Handles displaying the dev's information.
     *
     * @param evt button clicked
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(rootPane, """
                                                André Benquerer
                                                Student #24633 @ Instituto Politécnico de Tomar
                                                Computer Engineering - 3rd Year
                                                Contact: dev.benquerer@gmail.com
                                                Github: Benquerer
                                                """,
                "About the project", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/resources/fotDev1.jpg")));

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * Handles displaying the dev's information.
     *
     * @param evt button clicked
     */
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(rootPane, """
                                                Diogo Larangeira 
                                                Student #24993 @ Instituto Politécnico de Tomar
                                                Computer Engineering - 3rd Year
                                                Contact: aluno24993@ipt.pt
                                                """,
                "About Diogo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/resources/fotDev2.jpg")));
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * This handles the selection of a new accent color for the application
     *
     * @param evt menu item for accent color clicked
     */
    private void miAccColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAccColorActionPerformed
        try {
            //diplay color chooser to user
            Color accColor = JColorChooser.showDialog(null, "Pick a Color", Color.RED);
            //if a color was selected, use it
            if (accColor != null) {
                //convert the selected color to a hex string
                String hexColor = String.format("#%02x%02x%02x", accColor.getRed(), accColor.getGreen(), accColor.getBlue());;
                //set laf to use color as accent
                FlatLaf laf = (FlatLaf) UIManager.getLookAndFeel();
                laf.setExtraDefaults(Collections.singletonMap("@accentColor", hexColor));
                //set laf on uimanager
                UIManager.setLookAndFeel(laf);
                //update LaF
                SwingUtilities.updateComponentTreeUI(this);
                SwingUtilities.updateComponentTreeUI(AboutFrame);
                SwingUtilities.updateComponentTreeUI(RegisterFrame);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_miAccColorActionPerformed

    /**
     * This handles the knowledge base topic on the FlatLaf Library.
     *
     * @param evt menu selected
     */
    private void miAbtAsyCryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbtAsyCryActionPerformed
        try {
            //open the browser with information about the topic
            URI link = new URI(app_params.ABT_FLAF);
            Desktop.getDesktop().browse(link);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Can't access this information right now!\ntry again later!", "Can't open Link", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miAbtAsyCryActionPerformed

    /**
     * This handles the knowledge base topic on Asymmetric Encryption.
     *
     * @param evt menu selected
     */
    private void miAbrFlafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrFlafActionPerformed
        try {
            //open the browser with information about the topic
            URI link = new URI(app_params.ABT_ASCYPT);
            Desktop.getDesktop().browse(link);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Can't access this information right now!\ntry again later!", "Can't open Link", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_miAbrFlafActionPerformed

    //registration routine
    private void btnRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserActionPerformed
        if (txtRegUsername.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Please insert a username!", "Invalid Username", JOptionPane.WARNING_MESSAGE);
        } else if (String.valueOf(pwdfRegPass.getPassword()).isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Please insert a password!", "Invalid Password", JOptionPane.WARNING_MESSAGE);
        } else if (String.valueOf(pwdfRegConfPass.getPassword()).isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Please confirm the password!", "Invalid Confirmation Password", JOptionPane.WARNING_MESSAGE);
        } else if (!String.valueOf(pwdfRegPass.getPassword()).equals(String.valueOf(pwdfRegConfPass.getPassword()))) {
            JOptionPane.showMessageDialog(rootPane, "The passwords must be the same!", "Invalid Confirmation", JOptionPane.ERROR_MESSAGE);
        } else {
            //pega as informacoes
            String username = txtRegUsername.getText();
            String pwd = String.valueOf(pwdfRegPass.getPassword());

            try {
                //connectar no server
                IremoteP2P remote = (IremoteP2P) RMI.getRemote(txtRemoteAddress.getText());
                if (remote.userExists(username)) {
                    JOptionPane.showMessageDialog(rootPane, "Username already in use!", "Invalid Username", JOptionPane.ERROR_MESSAGE);
                    txtRegUsername.setText(""); 
                    pwdfRegPass.setText("");
                    pwdfRegConfPass.setText("");
                } else {
                    //pega a chave do server
                    KeyPair kp = SecurityUtils.generateRSAKeyPair(512);
                    byte[] secretServer = remote.getSimKey(kp.getPublic());
                    if (secretServer != null) {
                        //decripta a chave de comunicacao
                        byte[] simkeyServer = SecurityUtils.decrypt(secretServer, kp.getPrivate());
                        Key simServer = SecurityUtils.getAESKey(simkeyServer);
                        //encriptar pwd com a simetrica do server
                        byte[] secretPass = SecurityUtils.encrypt(pwd.getBytes(), simServer);
                        //registra utilizador no server
                        String created = remote.registerUser(username, secretPass, boxIsOrg.isSelected());
                        JOptionPane.showMessageDialog(rootPane, created, "User creation!", JOptionPane.INFORMATION_MESSAGE);
                    }
                    txtRegUsername.setText(""); 
                    pwdfRegPass.setText("");
                    pwdfRegConfPass.setText("");
                    boxIsOrg.setSelected(false);
                    RegisterFrame.dispose();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "An error occurred while registering the user!\n Please try again later.", "Registration Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnRegisterUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            //connectar no server
            IremoteP2P remote = (IremoteP2P) RMI.getRemote(txtRemoteAddress.getText());
            //pega as informacoes
            String username = txtLogin.getText();
            String pwd = String.valueOf(pwdfLogin.getPassword());
            //pega a chave do server
            KeyPair kp = SecurityUtils.generateRSAKeyPair(512);
            byte[] secretServer = remote.getSimKey(kp.getPublic());
            if (secretServer != null) {
                //decripta a chave de comunicacao
                byte[] simkeyServer = SecurityUtils.decrypt(secretServer, kp.getPrivate());
                Key simServer = SecurityUtils.getAESKey(simkeyServer);
                //encriptar pwd com a simetrica do server
                byte[] secretPass = SecurityUtils.encrypt(pwd.getBytes(), SecurityUtils.getAESKey(simkeyServer));
                Map<String, byte[]> encryptedKeys = remote.loginUser(username, secretPass);
                if (encryptedKeys != null) {
                    //save user credentials
                    byte[] decryptedPrivKey = SecurityUtils.decrypt(encryptedKeys.get("privateKey"), simServer);
                    byte[] decryptedPubKey = SecurityUtils.decrypt(encryptedKeys.get("publicKey"), simServer);
                    byte[] decryptedSimKey = SecurityUtils.decrypt(encryptedKeys.get("symmetricKey"), simServer);
                    byte[] decryptedProps = SecurityUtils.decrypt(encryptedKeys.get("props"), simServer);
                    //salvar as keys
                    //pubkey
                    Files.write(Path.of(username + ".pubk"), decryptedPubKey);
                    //privkey
                    byte[] secretPriv = SecurityUtils.encrypt(decryptedPrivKey, pwd);
                    Files.write(Path.of(username + ".privk"), secretPriv);
                    //simkey
                    byte[] secretSim = SecurityUtils.encrypt(decryptedSimKey, pwd);
                    Files.write(Path.of(username + ".simk"), secretSim);
                    //props
                    Files.write(Path.of(username + ".props"), decryptedProps);

                    User loggedUser = new User(username);
                    loggedUser.load(pwd);
                    if (loggedUser.isRegistrant()) {
                        
                        String hexColor = "#00ff00";
                        //set laf to use color as accent
                        FlatLaf laf = (FlatLaf) UIManager.getLookAndFeel();
                        laf.setExtraDefaults(Collections.singletonMap("@accentColor", hexColor));
                        //set laf on uimanager
                        
                        
                        UIManager.setLookAndFeel(laf);
                        
                        
                        RegistrantClient app = new RegistrantClient(loggedUser, UIManager.getLookAndFeel(), txtRemoteAddress.getText());
                        //hide login frame
                        this.setVisible(false);
                        txtLogin.setText("");
                        pwdfLogin.setText("");
                        //handle logout (quit appFrame without quiting se whole app)
                        app.addWindowListener(new WindowAdapter() {
                            @Override
                            public void windowClosed(java.awt.event.WindowEvent e) {
                                LoginFrame.this.setVisible(true);
                            }
                        });
                    } else {
                        ClientFrame app = new ClientFrame(loggedUser, UIManager.getLookAndFeel(), txtRemoteAddress.getText());
                        this.setVisible(false);
                        txtLogin.setText("");
                        pwdfLogin.setText("");
                        //handle logout (quit appFrame without quiting se whole app)
                        app.addWindowListener(new WindowAdapter() {
                            @Override
                            public void windowClosed(java.awt.event.WindowEvent e) {
                                LoginFrame.this.setVisible(true);
                            }
                        });
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Can't login with provided information!\n Please check the provided credentials", "Wrong Credentials", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "An error occurred!\n Please try again later.", "Login Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

        //lancar a pagina desejada
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * Main function of the application. This will set the custom LaF, create
     * and display the form, centering it on the screen.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Change LaF of application (Customized by FlatLaf library
        try {
            //set LaF MacOS Dark
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
            //LaF customization
            UIManager.put("Button.arc", 20);
            UIManager.put("Component.arc", 20);
            UIManager.put("TextComponent.arc", 20);
            UIManager.put("Component.focusWidth", 1);
            UIManager.put("Component.arrowType", "chevron");
        } catch (Exception e) {
            e.printStackTrace();
        }

        //create and display form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //build and set frame visible
                LoginFrame loginFrame = new LoginFrame();
                loginFrame.setVisible(true);
                //center on screen
                loginFrame.setLocationRelativeTo(null);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Variables declaration"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AboutFrame;
    private javax.swing.JFrame RegisterFrame;
    private javax.swing.JCheckBox boxIsOrg;
    private javax.swing.JButton btnCancelReg;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JCheckBoxMenuItem chkboxColorMode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JMenu mMain;
    private javax.swing.JMenuBar mbarX;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miAbrFlaf;
    private javax.swing.JMenuItem miAbtAsyCry;
    private javax.swing.JMenuItem miAbtBc;
    private javax.swing.JMenuItem miAccColor;
    private javax.swing.JMenu miKnowlBase;
    private javax.swing.JMenuItem miRegister;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl7;
    private javax.swing.JPanel pnl8;
    private javax.swing.JPasswordField pwdfLogin;
    private javax.swing.JPasswordField pwdfRegConfPass;
    private javax.swing.JPasswordField pwdfRegPass;
    private javax.swing.JPopupMenu.Separator sp1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtRegUsername;
    private javax.swing.JTextField txtRemoteAddress;
    // End of variables declaration//GEN-END:variables
    // </editor-fold> 
}
